name: Crear archivo JSON con secreto

on:
  push:
    branches:
      - main

jobs:
  crear-archivo-json:
    runs-on: ubuntu-latest
    

    steps:
        env:
      - name: Crear archivo JSON con secreto
        run: echo " prueba 5001 ${{ vars.GCP2 }}" > secret.json

      - name: Guardar archivo JSON como artefacto
        uses: actions/upload-artifact@v2
        with:
          name: secret
          path: secret.json
